In [2]:
import numpy as np

## Iterate over each number in the input vector n times, n being the number of columns in the o/p matrix and output 
## an intermediate vector. Use diff order formula based on increasing and decreasing condition.
## Reshape the intermediate vector using the size of the input vector (rows) and n (columns) to generate the o/p matrix. 
   
def gen_vander_matrix(ipvector, n, increasing=False):
    
    if not increasing:
        op_matx = np.array([x**(n-1-i) for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    elif increasing:
        op_matx = np.array([x**i for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    
    return op_matx

print("------------OUTPUT-------------\n")

inputvector = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
no_col_opmat = 3
op_matx_dec_order = gen_vander_matrix(inputvector,no_col_opmat,False)
op_matx_inc_order = gen_vander_matrix(inputvector,no_col_opmat,True)

print("The input array is:",inputvector,"\n")
print("Number of columns in output matrix should be:",no_col_opmat,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",op_matx_dec_order,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",op_matx_inc_order,"\n")

inputvector = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
no_col_opmat = 5
op_matx_dec_order = gen_vander_matrix(inputvector,no_col_opmat,False)
op_matx_inc_order = gen_vander_matrix(inputvector,no_col_opmat,True)

print("---------------------------------------------------------------\n")
print("The input array is:",inputvector,"\n")
print("Number of columns in output matrix should be:",no_col_opmat,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",op_matx_dec_order,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",op_matx_inc_order,"\n")

------------OUTPUT-------------

The input array is: [  3   5   7   2   8  10  11  65  72  81  99 100 150] 

Number of columns in output matrix should be: 3 

Vander matrix of the input array in decreasing order of powers:

 [[    9     3     1]
 [   25     5     1]
 [   49     7     1]
 [    4     2     1]
 [   64     8     1]
 [  100    10     1]
 [  121    11     1]
 [ 4225    65     1]
 [ 5184    72     1]
 [ 6561    81     1]
 [ 9801    99     1]
 [10000   100     1]
 [22500   150     1]] 

Vander matrix of the input array in increasing order of powers:

 [[    1     3     9]
 [    1     5    25]
 [    1     7    49]
 [    1     2     4]
 [    1     8    64]
 [    1    10   100]
 [    1    11   121]
 [    1    65  4225]
 [    1    72  5184]
 [    1    81  6561]
 [    1    99  9801]
 [    1   100 10000]
 [    1   150 22500]] 

---------------------------------------------------------------

The input array is: [  3   5   7   2   8  10  11  65  72  81  99 100 150] 

Number of column